language: go

go:
  - 1.8

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
  - go get -u github.com/golang/dep/cmd/dep
  - gometalinter --install
  - dep ensure

script:
  - gometalinter --disable golint --disable gocyclo --disable gas xmmsclient
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=xmmsclient/auto*.go,genipc/*,examples/*/*
