language: go

go:
  - 1.7

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
  - go get github.com/stretchr/testify
  - go get github.com/leanovate/gopter
  - gometalinter --install

script:
  - gometalinter --disable golint --disable gocyclo --disable gas xmmsclient
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=xmmsclient/auto*.go,genipc/*,examples/*/*
